version: '3.4'

services:
  medicalencounters.api:
    image: ${DOCKER_REGISTRY-}medicalencountersapi
    container_name: medicalencounters.api
    build:
      context: .
      dockerfile: MedicalEncounters.Api/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"

  medicalencounters.database:
    image: postgres:latest
    container_name: medicalencounters.database
    environment: 
        - POSTGRES_DB=medicalencounters
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Init db
    ports:
        - 5432:5432
  
  
         
